name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18', '20', '21']
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm i
      - run: npm test
